---
# roles/svi_config/tasks/main.yml

- name: Enable Layer 3 routing
  ios_config:
    lines:
      - ip routing
  notify: Save config

- name: Ensure generated_configs directory exists
  file:
    path: generated_configs
    state: directory
    mode: '0755'

- name: Generate SVI config file locally
  template:
    src: svi.j2
    dest: "generated_configs/{{ inventory_hostname }}-svi.cfg"

- name: Configure SVIs
  ios_config:
    src: svi.j2
  notify: Save config
