all:
  children:
    network_devices:
      children:
        routers:
          hosts:
            CRT:
              ansible_host: 192.168.122.11

        switches:
          children:
            distribution:
              hosts:
                DSW:
                  ansible_host: 192.168.122.10

            access:
              hosts:
                ASW:
                  ansible_host: 192.168.122.13

  vars:
    ansible_user: Elvis
    ansible_password: Cisco
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: Cisco
