---
vlans:
  - { id: 10, name: users }
  - { id: 20, name: voice }
  - { id: 30, name: HR }
  - { id: 100, name: Data }



vtp_domain:  "mycorp"
vtp_password: "cisco"
vtp_version: 2

vtp_mode:
  DSW: server
  ASW: client
  CRT: transparent   # optional but recommended

trunks:
  ASW:
    - { interface: Gig0/1 }
  DSW:
    - { interface: Gig0/1 }
    - { interface: Gig0/2 }

svis:
  - { vlan: 10, ip: 192.168.10.1 255.255.255.0 }
  - { vlan: 20, ip: 192.168.20.1 255.255.255.0 }
